params:
  learning_rate:
    - 1e-3
  weight_decay:
    - 1e-2
  seed:
    - 0
    #- 1
    #- 2
    #- 3
    #- 4
  long_range:
    - 10
  batch_size:
    - 1
  scheduler:
    - true
  model_id:
    - "L"
  kernel_size:
    - 5
  synthetic:
    - 1.0
  drop_slice_prob:
    - 0.05
  shift_slice_prob:
    - 0.05
  intensity_aug:
    - true
  noise_scale:
    - 0.5
  affine:
    - 0.5
  n_steps:
    - 1_000_000
  small_size:
    - 256
  data_setting:
    #- "base"
    #- "liconn"
    #- "multichannel"
    #- "neg_guidance"
    #- "no_touch_thick"
    #- "pos_guidance"
    #- "slice_perturbed"
    #- "touching_thin"
    - "train_100"
  base_data_path:
    - "/cajal/nvmescratch/projects/NISB/"
  save_path:
    #- "/cajal/scratch/projects/misc/riegerfr/aff_nis/"
    - "/cajal/scratch/projects/misc/zuzur/xl_banis"
  exp_name:
    - "xl_test"
  real_data_path: #https://colab.research.google.com/github/funkelab/lsd/blob/master/lsd/tutorial/notebooks/lsd_data_download.ipynb
    - "/cajal/scratch/projects/misc/mdraw/data/funke/zebrafinch/training/"
  auto_resubmit:
    - True
  distributed:
    - True
  compile:
    - False
  validate_extern:
    - True